### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Shylock-Hg** [williamcanin/williamcanin.github.io#1]
The tag string with *space* or *uppercase letter* won't jump well.

**Comment by williamcanin** [comment]
@Shylock-Hg  Which Bug is it specifically saying? That definition is vague. Thank you.

**Comment by Shylock-Hg** [comment]
When the **tag** name string contain **space** or **uppercase** letter,the page of collection of blogs corresponding to the tag is **404**..

**Comment by williamcanin** [comment]
@Shylock-Hg What project are you talking about? You are sending Issues to the repository where my personal page is stored, this repository is not a project. By the way, you're talking about the "[**Typing**](https://github.com/williamcanin/typing-jekyll-template)" template?

**Comment by Shylock-Hg** [comment]
Sorry.
Yes, what I said is Typing template.

**Comment by williamcanin** [comment]
Transferred to https://github.com/williamcanin/typing-jekyll-template/issues/9
